<script lang="ts">
import { onMount } from 'svelte';
import * as Tabs from '$lib/components/ui/tabs';

let countSync = 0;
const link = 'https://github.com/guocaoyi/create-chrome-ext';

onMount(() => {
	chrome.storage?.sync.get(['count'], (result) => {
		countSync = result.count || 0;
	});

	chrome.runtime?.onMessage.addListener((request) => {
		if (request.type === 'COUNT') {
			countSync = request?.count ?? 0;
		}
	});

	if (
		window.matchMedia &&
		window.matchMedia('(prefers-color-scheme: dark)').matches
	) {
		// The user prefers dark mode
		document.documentElement.classList.add('dark');
	}

	// Listen for changes to the user's preferred color scheme
	window
		.matchMedia('(prefers-color-scheme: dark)')
		.addEventListener('change', (e) => {
			if (e.matches) {
				// The user now prefers dark mode
				document.documentElement.classList.add('dark');
			} else {
				// The user now prefers light mode
				document.documentElement.classList.remove('dark');
			}
		});
});
</script>

<main>
	<h3>SidePanel Page</h3>

	<h4>Count from Popup: {countSync}</h4>

	<a href={link} target="_blank"> generated by create-chrome-ext </a>

	<Tabs.Root value="account" class="w-full">
		<Tabs.List>
			<Tabs.Trigger value="account">Account</Tabs.Trigger>
			<Tabs.Trigger value="password">Password</Tabs.Trigger>
		</Tabs.List>
		<Tabs.Content value="account">
			Make changes to your account here.
		</Tabs.Content>
		<Tabs.Content value="password">Change your password here.</Tabs.Content>
	</Tabs.Root>
</main>

<style lang="postcss">
@import '../app.pcss';

:global(:root) {
	font-family:
		system-ui,
		-apple-system,
		BlinkMacSystemFont,
		'Segoe UI',
		Roboto,
		Oxygen,
		Ubuntu,
		Cantarell,
		'Open Sans',
		'Helvetica Neue',
		sans-serif;

	color-scheme: light dark;
}

@media (prefers-color-scheme: light) {
	a:hover {
		color: #ff3e00;
	}
}

:global(body) {
	min-width: 20rem;
	margin: 0;
}

main {
	text-align: center;
	padding: 1em;
	margin: 0 auto;
}

h3 {
	color: #ff3e00;
	text-transform: uppercase;
	font-size: 1.5rem;
	font-weight: 200;
	line-height: 1.2rem;
	margin: 2rem auto;
}

a {
	font-size: 0.5rem;
	margin: 0.5rem;
	color: #cccccc;
	text-decoration: none;
}
</style>
